### ISSUE TITLE
create_excel_rows: how to input data to produce multiple outputs based on topic

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/json-to-excel-flow#7]
In the first part of the script a list of objects is defined to specify how to subdivide the flows into output files:

 cat_file_names = [];

cat_file_names.push({ flow_cat_name: "PLH - Help", file_name: "help" })
cat_file_names.push({ flow_cat_name: "PLH - Content - Relax", file_name: "content-relax" });
cat_file_names.push({ flow_cat_name: "PLH - Content - Extra", file_name: "content-extra" });
cat_file_names.push({ flow_cat_name: "PLH - Content - Time", file_name: "content-time" });
etc

flow_cat_name is the string that allows to identify the flows for a given category (in this case it's the initial part of the flow name, but we could maybe generalise it to a REGEX or something similar?) 
file_name is the name of the output json file, where the keys are the names of the flows and the values the lists of row objects

We should probably remove this part from the script and require the info as an input and if there is no input then a single json file should be outputted with a default name? or maybe this case should fall in the "other" case (see below)

The second issue is that I need all the remaining flows (those whose name does not fall in any of the category) to be all outputted in a json called "other" or something similar.  At the moment this is achieved by commenting out some lines of code (the current version of the script is for producing other) while the file should be produced running a single script that includes both cases

**Comment by istride** [comment]
My suggestion is that we move that mapping from flow name prefixes to file names into a separate JSON file. In essence, the script would be called like this:

```
create_excel_rows.js <input_file> <mapping_file> <output_dir>
```

- `input_file` is the Rapid Pro JSON export.
- `mapping_file` describes how to split up the Rapid Pro flows.
- `output_dir` is the directory where the output JSON files will go.

The mapping file will be another JSON file, whose contents could be as follows:
```json
{
  "default_file_name": "other",
  "mappings": [
    { "flow_cat_name": "PLH - Help", "file_name": "help" },
    { "flow_cat_name": "PLH - Content - Relax", "file_name": "content-relax" },
  ]
}
```

This covers the default case (`default_file_name`) as well as the existing mappings. Does this make sense?
