### ISSUE TITLE
create_single_excel: problem with empty flow

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/json-to-excel-flow#8]
(NOTE: I don't know if this is true also for the new .js script)
The current python script doesn't handle the case of an empty flow (one of the PLH flows is empty because we use it for A/B testing), so I need to delete the empty intermediary csv file before running it. Probably the issue is also in the fact that the csv is empty, while it should probably contain at least the column names?

**Comment by istride** [comment]
I tried `create_single_excel.js` with three empty CSV files.

```
json-to-excel
└── csv
    ├── 1.csv
    ├── 2.csv
    └── 3.csv
```

The result is an XLSX spreadsheet with 3 sheets (called "1", "2", and "3") with no data in them. Is this correct, or should the spreadsheet have no sheets in it and no data?

Could the problem be that a CSV is being created for an empty flow, when perhaps no CSV should be created instead?

**Comment by fagiothree** [comment]
I think that the root of the problem is in the fact that for an empty flow we should produce a csv with only the column names (and I am not sure this is currently the case, it's probably just an empty file). Then, in the excel, this should correspond to a sheet with only the column names, which I think is the correct representation of an empty flow.
